### ISSUE TITLE
AM I LOSING IT? 

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#11]
@mbjoseph can i push directly to this repo? It's telling me i can't BUT it is very possible i am missing something.

**Comment by lwasser** [comment]
you can answer "yes" and i won't be offended btw

**Comment by mbjoseph** [comment]
`git pull`?

**Comment by lwasser** [comment]
It's telling me I don't have permissions. Pull was fine. I'll try again tomorrow on my laptop. weird. I thought I had pushed directly previously

**Comment by lwasser** [comment]
ok - weirdness - restarting everything fixed whatever happened :) closing this!!

**Comment by mbjoseph** [comment]
Huh. That's super weird.

**Comment by lwasser** [comment]
i'm convinced it had to do with the DOS attack!!
