### ISSUE TITLE
meetup site / events - potential duplication or opportunity to merge?

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#18]
hey @mbjoseph i just found this site

https://earthlab.github.io/meetup/

it seems to have some events already?? it's a cool page but do we want to have another site? and will all events be here. lemme know what makes sense! i'd like to be able to list the next meetup topic on our site if it's at all possible? is it?

**Comment by mbjoseph** [comment]
I like the idea of merging the sites, but then we lose the issue tracking functionality that provides a forum to discuss the meetup, and the repo "Watch" functionality that gives people notifications.... 

What if we moved the web portion over to this repository and broadened the scope from meetups to events in general, but kept the earthlab/meetup repository as a place to open issues related to the meetup?

**Comment by lwasser** [comment]
Hi there.
I totally see why you'd want to keep the repo. It's just the front end Web part which has event pages that I think could be merged if you're open to it. I'd then suggest we make events a collection and we can use those MD pages to seed our events page.

But please let me know if any of this impacts the meetup structure! I just started thinking about events and got confused when I saw another live site w events.

**Comment by mbjoseph** [comment]
How about this? 

https://github.com/earthlab/dev-earthlab-site/tree/events-page

This uses an events collection and just lists them by date, divided by future and past events.

**Comment by lwasser** [comment]
I see the collection. Where is the landing page?
I am on my phone and could be missing something too!

Btw I need to push some edits up to the landing page for the learn section too! I just realized I forgot to push yesterday!

**Comment by lwasser** [comment]
Ok I found it. Events.MD I think that will be good!! Git branches look funny on a phone. Took a minute to find the code.

**Comment by lwasser** [comment]
ok -- i've added events to the top bar and created a dummy landing page just to test but feel free to overwrite it! Or just user the header as a call to action and add your code or whatever. 

https://earthlab.github.io/dev-earthlab-site/events/

l.

**Comment by mbjoseph** [comment]
Great - I just merged our changes together and next I need to:
- [x] shut down the existing meetup website
- [x] redirect the call to action url to the GitHub repo for the meetup

**Comment by lwasser** [comment]
sounds good. Leave the repo but shut down the live site. is that correct?

question - right now the site links to the meetup ISSUE. do you want that OR a link to a page about the event like you have on the meetup site now?

**Comment by mbjoseph** [comment]
Yes that's correct - I still want to keep the issue tracking functionality, but don't need the old earthlab.github.io/meetup page. 

For the meetup, I'd like to link to the issue, but for other events, we may want to have a page for each one. Do you have any ideas for how we might do this?

**Comment by mbjoseph** [comment]
OK I have shut down the old meetup page which was built from the `earthlab/meetup` repo, and now we're building the meetup page from `_posts/meetup.md` in this repository.
