### ISSUE TITLE
classroom lab vs tutorial

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#24]
Hi @mbjoseph . I've been contemplating how to push my lab materials to our site. Here is the thing. A class lab is quite different from a tutorial and i'd like to list them as such. I've coded a nice little side bar that lists presentations and lessons in an automated way - yay!

With that said - are you ok with adding another link to the top bar called "classroom" Or labs or something. i'm super open to what we call it. shorter is better. Then I can list each lesson on that page AND we can create a nice XML feed with only those items. eventually we may have a classes item that could replace labs. but for now.... labs may work.

NOTE: this doesn't affect ANY of the work you've been doing on the tutorials!! promise! It's all me thinking about requirements and use cases for these lessons. Thoughts? i'm happy to show you tomorrow. i haven't pushed anything up to dev yet but have it working local.

**Comment by mbjoseph** [comment]
I see what you're saying. I think a "Lab" or "Course material" link would be nice. I'll be in tomorrow morning if you want to show me what you're thinking (but I'll be gone in the afternoon).

**Comment by lwasser** [comment]
Ok! I’m meeting with Brian Johnson remotely in the morning to talk about permafrost and data lessons for my course. I’ll be in after that – I’m hoping by 11:30 or so? I’ll look for you and if it’s too late, I’ll push up the open science template which I just redid with the automation and will send you the link! ☺

If we do this I’ll want to build a course material landing page with some custom layout stuff. It won’t take long to do and will be a perfect project for the plane next week.

**Comment by lwasser** [comment]
ok - i've pushed this to a new branch - courses

https://github.com/earthlab/dev-earthlab-site/tree/courses

i don't love having that may links on the top. one option is to remove earth lab home and make a little icon above that. let me know what you think. I'm going to code a new side bar for the course materials page (that doesn't have R and python).

**Comment by lwasser** [comment]
I implemented this today. if you are ok with it, can we close this issue @mbjoseph  ? i'm going to work on sidebar styling on the plane tomorrow. 

https://earthlab.github.io/dev-earthlab-site/course-materials/

**Comment by mbjoseph** [comment]
Looks friggin awesome to me.

**Comment by lwasser** [comment]
Heck yeaaahhhhhh! I'm happy with it too. Thanks for the positive feedback!

## Leah A. Wasser

Director, Earth Analytics Education Initiative
Earth Lab, CU Boulder
twitter: @leahawasser
