### ISSUE TITLE
Are some tutorials not R or Python?

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#25]
@mbjoseph  - I'm noticing that we have more tutorials in the list than ones counted in the languages on the side bar.

**Comment by mbjoseph** [comment]
Yep we've got a couple in javascript (for Google Earth Engine)
- https://github.com/earthlab/dev-earthlab-site/blob/master/_posts/documentation/2016-09-01-intro-google-earth-engine-ide.md
- https://github.com/earthlab/dev-earthlab-site/blob/master/_posts/documentation/2016-10-01-basic-polygon-operations-google-earth-engine.md

**Comment by lwasser** [comment]
Ok - when we have a new language we need to

1. add it to the _data/libs.yml file
2. create a languagename.md file in org/category/lang

And then it will work - i still need to fix the side bar to accommodate another language AND fix the styles which are butt ugly now. i'll do that on the plane tomorrow :)
fixed  403517a - closing!
