### ISSUE TITLE
internal tools page

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#26]
hi @mbjoseph -- what is this page - it's link to on the tools page but i can't seem to find it anywhere? Does it exist? do we need to make it? 

https://earthlab.github.io/dev-earthlab-site/tools/

**Comment by mbjoseph** [comment]
I removed the link in ce3c1f125b258f4282cf0a9cf90568b583afd3e7

**Comment by lwasser** [comment]
YEEAAASSS. I was crying at night because I couldn’t find it. Thank goodness I’ll sleep tonight.

**Comment by mbjoseph** [comment]
lol
