### ISSUE TITLE
Do you prefer max vs maxwell?

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#27]
hey @mbjoseph - we have both in the site. which do you prefer? Whichever you prefer we should use that on all lessons.

```
- name: Max Joseph
  slug: max-joseph
- name: Maxwell Joseph
  slug: maxwell-joseph
```

**Comment by mbjoseph** [comment]
I''d go with Max, despite risk of confusion with this guy: http://www.mtv.com/news/2950108/catfish-max-joseph-nev-schulman-baby-girl/

**Comment by lwasser** [comment]
HAHA – ok. Nothing like some quality bonding. I’ll manually fix the .md files but you may need to adjust on the notebook end. No need to rebuild BUT it will be an issue if you rebuild in the future and we have both! Does that work? If it makes you feel better there were two leah wasser spellings too ☺ catching lots of little things – but we’re close to a live push!
l.

**Comment by lwasser** [comment]
fixed. closing
