### ISSUE TITLE
can i please have admin access to the dev site?

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#3]
Hey @mbjoseph  - can you please give me superpowers to the dev site? i just transferred. it.

**Comment by mbjoseph** [comment]
Superpowers granted!

![](https://s-media-cache-ak0.pinimg.com/564x/55/40/7d/55407d754bd0ca45bd8fc499d37f2aef.jpg)

**Comment by lwasser** [comment]
yeaaasssss! thx. 👍
