### ISSUE TITLE
One post is breaking our RSS feed

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#35]
Hey @mbjoseph -- the file: _posts/python/2016-07-05-creating-animated-maps-matplotlib-basemap.md is breaking our RSS feed. i'm not sure why. the YAML is ok so something in the code on the page is breaking it. in ATOM the file completely hangs up.

To fix this we have two options

1. you figure out why it's breaking the feed - it is something with the output md that is breaking it
2. A quick lazy fix for the RSS feed  - i add a YAML element that tells the rss feed to ignore this one post so the feed works. 

i'm happy to do #2 to get the site up unless you have time to figure out 1 in the next week? Let me know! This won't affect the site and the feed on the website given this is an older post.

**Comment by mbjoseph** [comment]
Very weird. This post has an interactive graphic, but it doesn't render on Jekyll. I think option 2 is probably our best bet.

**Comment by lwasser** [comment]
temporarily turning off this post in the feed via an if clause using the title as the filter. 

67b777272032dd3953ea86bf6a204ea224644760

it is a hack but for now, it is good enough to get the site up and running. closing this issue.

**Comment by mbjoseph** [comment]
![](http://weknowmemes.com/wp-content/uploads/2014/09/this-is-fine-meme.jpg)

**Comment by mbjoseph** [comment]
![](http://i0.kym-cdn.com/entries/icons/original/000/018/012/Screen_Shot_2015-05-12_at_3.31.31_PM.png)

**Comment by lwasser** [comment]
:/ too much goin on? Lemme know if the website stuff is too much!

**Comment by mbjoseph** [comment]
It's fine - just making a joke! I have pushed the site https://earthlab.github.io/ (not sure whether you saw this)

**Comment by lwasser** [comment]
I didn’t – I’ll check it out! I’ll update the feeds on the website and will remove a few lessons that I’m working on that are under dev. I forgot I didn’t want to push them just yet!!
Yay!
