### ISSUE TITLE
question: does the repo build automagically?

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#40]
Hey @mbjoseph i just noticed that there are new author and lib files in our repo!! this is very cool. My question -- does the build happen automagically or is this a make workflow locally?

Perhaps you can show me later today.
If I add some text to one of the author pages, will it be overwritten? Or does the file look to see if it's there and ONLY build it if it's missing.

Thank you!

**Comment by mbjoseph** [comment]
"Hey @lwasser": it happens when we run `make`, which executes this script: https://github.com/earthlab/dev-earthlab-site/blob/master/processing-code/validate_authors.R

**Comment by mbjoseph** [comment]
Which is to say - yes if you manually edit these, they will get overwritten. Are you trying to add bios? If so, we could stick those in another file (e.g., even plain text) and read those in when the files are generated.

**Comment by lwasser** [comment]
@mbjoseph yes please. When we meet today i'll gladly build a csv with Name, Slug and bio. talk later. we could use the 2pm slot now too if you want. i'm easy in terms of schedule today!

**Comment by lwasser** [comment]
to discuss

- [ ] Adding bios to author pages - (needs to support markdown)
- [ ] keeping material current
- [ ] Multiple repo deployment?

**Comment by lwasser** [comment]
i'm closing this - question answered!
