### ISSUE TITLE
LICENSE Our materials - FILE added, is the text ok

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#41]
Attributing all of our content as CC-BY 4.0 license. Need to add this to our layout so it's at the bottom of all pages.  To do's

- [x] @mbjoseph please review the license and make sure it seems INLINE with earth lab's rules / mission / etc Particularly the software part. We could remove that if you aren't comfortable with it.
- [x] I need to add a chunk of code so a link to the license renders at the bottom of all of our class lessons (and tutorials? )

**Comment by mbjoseph** [comment]
I'm very much on board with the CC-BY license. :+1:

**Comment by lwasser** [comment]
Sweet. Well maybe we should consider the wtfppl license too then. I use that license a lot.

I'll add links to the bottom of all tutorials and course materials today then!

________________________________

**Comment by lwasser** [comment]
boo yah!

d0e45a79a9374790083af4d3e9fff21be71581f3
