### ISSUE TITLE
Create Example Tool landing page

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#6]
@mbjoseph can you please create a dummy tool landing .md page that describes a cool tool you've built with a link to it? I'll then create a template for posting it.

**Comment by lwasser** [comment]
@mbjoseph you will likely have more than 3 tools, correct?

**Comment by mbjoseph** [comment]
Definitely. As more are added I think it just creates new rows and keeps 3
columns/row.

**Comment by lwasser** [comment]
ok -- you can do it this way but it's a bit less search engine savy as we don't have landing pages for each tool with an explanation of what they do and then links to git. 

https://mmistakes.github.io/minimal-mistakes/docs/layouts/ 

Check out the grid layout. If you create a page for each tool with a description and image in the YAML, we can generate landing pages per tool. this is a searchable thing on our site and can be placed into a grid. what do you think about that? that way we aren't curating a yaml list of things, rather pages with descriptive content about the tool.

**Comment by mbjoseph** [comment]
That's nice looking - and I like that it doesn't clutter up the front matter. I'll take a stab at this and submit another PR.

**Comment by lwasser** [comment]
Sweet.
I’m pretty happy he built that layout. I’ve always wanted it and tried several times unsuccessfully to create something that was responsive and nice !
Hipster genious.

**Comment by mbjoseph** [comment]
Ok - I just merged the PR - how does this look? Can we close this issue?

**Comment by lwasser** [comment]
this page? looks awesome!!

https://earthlab.github.io/dev-earthlab-site/tools/

How did you get the git build info for smapr to appear? that's some cool magic right there.
I think down the road I may resize some of the banner graphics for the tool landing pages. But i say let's close this issue!!! yes! :)

**Comment by mbjoseph** [comment]
Badge magic:

```
[![Build Status](https://travis-ci.org/earthlab/smapr.svg?branch=master)](https://travis-ci.org/earthlab/smapr) 
[![CRAN\_Status\_Badge](http://www.r-pkg.org/badges/version/smapr)](https://cran.r-project.org/package=smapr) 
[![Licence](https://img.shields.io/badge/licence-GPL--2-blue.svg)](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html) 
[![Last-changedate](https://img.shields.io/badge/last%20change-2016--10--07-brightgreen.svg)](/commits/master)
```

**Comment by lwasser** [comment]
Saweeeettttttt!
